version: '3'
tasks:
  default:
    requires:
      vars:
        - NAME
        - GROUP
    cmds:
      - task: erase
      - task: flash
      - sleep 5
      - task: bootstrap
      - task: configure
        vars:
          SERVER: "nats://10.60.0.30:4222"
          SSID: "triggerwear"
          PASSWORD: "spacehacker"
          SSID_HIDDEN: 0
          VERSION: "IRA-BOX24"
      - mpremote reset

  erase:
    cmd: esptool.py --chip esp32 --baud 460800 --port /dev/cu.usbserial-110 erase_flash

  flash:
    cmd: esptool.py --chip esp32 --baud 460800 --port /dev/cu.usbserial-110 write_flash -z 0x1000 ~/Downloads/ESP32_GENERIC-SPIRAM-20231005-v1.21.0.bin

  bootstrap:
    dir: "firmware"
    cmds:
      - "echo '0.0.0' > version"
      - "mpremote fs cp -r ira :"
      - "mpremote fs cp -r fx :"
      - "mpremote fs cp -r tarfile :"
      - "mpremote fs cp main.py :"
      - "mpremote fs cp uota.cfg :"
      - "mpremote fs cp uota.py :"
      - "mpremote fs cp utils.py :"
      - "mpremote fs cp version :"

  upload:
    dir: "firmware"
    cmds:
      - "mpremote fs cp -r ira :"
      - "mpremote fs cp -r fx :"
      - "mpremote fs cp -r tarfile :"
      - "mpremote fs cp main.py :"
      - "mpremote fs cp uota.cfg :"
      - "mpremote fs cp uota.py :"
      - "mpremote fs cp utils.py :"
      - "mpremote fs cp version :"

  configure:
    requires:
      vars:
        - NAME
        - VERSION
        - GROUP
        - SSID
        - PASSWORD
        - SSID_HIDDEN
        - SERVER
    vars:
      HARDWARE: "ira"
    cmd: mpremote exec 'from ira.config import Config; c = Config(); c.set_device_name("{{.NAME}}"); c.set_device_hardware("{{.HARDWARE}}"); c.set_device_version("{{.VERSION}}"); c.set_device_group("{{.GROUP}}"); c.set_wifi_ssid("{{.SSID}}"); c.set_wifi_password("{{.PASSWORD}}"); c.set_server("{{.SERVER}}"); c.persist()'

  package:
    dir: "firmware"
    requires:
      vars:
        - VERSION
    cmds:
      - "echo {{.VERSION}} > version"
      - "mkdir ../build || true"
      - "tar -czf ../build/firmware-{{.VERSION}}.tar.gz *"
      - "echo '{{.VERSION}};firmware-{{.VERSION}}.tar.gz' > ../build/latest"