version: '3'
tasks:
  erase:
    cmd: esptool.py --chip esp32 --port /dev/cu.usbserial-210 erase_flash

  flash:
    cmd: esptool.py --chip esp32 --port /dev/cu.usbserial-210 --baud 460800 write_flash -z 0x1000 ~/Downloads/ESP32_GENERIC-SPIRAM-20231005-v1.21.0.bin

  bootstrap:
    dir: "firmware"
    cmds:
      - "echo '0.0.0' > version"
      - "mpremote u0 fs cp -r ira :"
      - "mpremote u0 fs cp -r fx :"
      - "mpremote u0 fs cp -r tarfile :"
      - "mpremote u0 fs cp main.py :"
      - "mpremote u0 fs cp uota.cfg :"
      - "mpremote u0 fs cp uota.py :"
      - "mpremote u0 fs cp utils.py :"
      - "mpremote u0 fs cp version :"

  configure:
    requires:
      vars:
        - NAME
        - VERSION
        - GROUP
    vars:
      HARDWARE: "ira"
      SSID: "triggerwear"
      PASSWORD: "spacehacker"
    cmd: mpremote exec 'from ira.config import Config; c = Config(); c.set_device_name("{{.NAME}}"); c.set_device_hardware("{{.HARDWARE}}"); c.set_device_version("{{.VERSION}}"); c.set_device_group("{{.GROUP}}"); c.set_wifi_ssid("{{.SSID}}"); c.set_wifi_password("{{.PASSWORD}}"); c.persist()'

  package:
    dir: "firmware"
    requires:
      vars:
        - VERSION
    cmds:
      - "echo {{.VERSION}} > version"
      - "mkdir ../build || true"
      - "tar -czf ../build/firmware-{{.VERSION}}.tar.gz *"
      - "echo '{{.VERSION}};firmware-{{.VERSION}}.tar.gz' > ../build/latest"